
@echo off

REM !!! Generated by the fmp-cli 1.88.0.  DO NOT EDIT!

md QuickBar\Assets\3rd\fmp-xtc-quickbar

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-quickbar-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\QuickBar\Assets\3rd\fmp-xtc-quickbar\
